name = "Modpack May"
author = "Zak"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9992ceb20346411c47b023e01e08dc642615102ebd5d7b66b4c424da85bb7ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
