name = "Modpack May"
author = "Zak"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06a8d66d456d07273c584a7a58529de776c0658363865dde3aa5af836076e536"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
