name = "Modpack May"
author = "Zak"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "225c0fa660cd43b562a4a9209b63bf4e79488402d2fe2282cf63a1d0b7113b19"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
