# Modified by Draconic Evolution Render Patcher
# allowUnknownShaders can be set to true by Draconic Evolution Render Patcher to ensure proper rendering of Draconic Evolution entities.
# Draconic Evolution Render Patcher will override allowUnknownShaders value in this file to enable this feature.
# Disable this behavior in Draconic Evolution Render Patcher's config if undesired.

#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 24 17:29:16 BST 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.8.1 + EuphoriaPatches_1.9.2
